### GET
GET http://localhost:9090/transactions

### GET
GET http://localhost:9090/banks

### GET
GET http://localhost:9090/banks/BRI

### GET
GET http://localhost:9090/banks/fee/BRI/2000000

### GET
GET http://localhost:9090/account

### POST
POST http://localhost:9090/transactions
Content-Type: application/json

{
  "login_status": true,
  "bank_id": "BRI",
  "transaction_status": true,
  "transaction_amount": 10000.0,
  "balance": 200.0
}

### POST
POST http://localhost:9090/banks
Content-Type: application/json

{
  "bank_id": "Mandiri",
  "bank_percentage": 0.3
}

### POST
POST http://localhost:9090/account
Content-Type: application/json

{
    "account_id": "SWE1809941",
    "account_name": "SamuelRussell"
}