### GET
GET http://localhost:9090/transactions

### GET
GET http://localhost:9090/transactions

### GET
GET http://localhost:9090/transactions/banks/goBCA

### POST
POST http://localhost:9090/transactions
Content-Type: application/json

{
  "login_status": true,
  "bank_id": "BCA",
  "transaction_status": true,
  "transaction_amount": 80.0,
  "balance": 200.0
}